/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false` (hash: feb0591f518736a358e41cf713e2d91b)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
		durableNamespaces: "SessionDurableObject" | "AuctionRoomDO";
	}
	interface Env {
		WEBAUTHN_APP_NAME: "auction-platform";
		WEBAUTHN_RP_ID: "auction.digitalglue.dev" | "staging-auction.digitalglue.dev";
		SESSION_DURABLE_OBJECT: DurableObjectNamespace<import("./src/worker").SessionDurableObject>;
		AUCTION_ROOM: DurableObjectNamespace<import("./src/worker").AuctionRoomDO>;
		IMAGES: R2Bucket;
		DB: D1Database;
		IMPORT_QUEUE: Queue;
		BID_EVENTS_QUEUE: Queue;
		ASSETS: Fetcher;
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "WEBAUTHN_APP_NAME" | "WEBAUTHN_RP_ID">> {}
}
