/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false` (hash: effa70520090a0d3d8aaf892845f64b7)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
		durableNamespaces: "SessionDurableObject" | "AuctionRoomDO" | "LiveStore";
	}
	interface Env {
		WEBAUTHN_APP_NAME: "auction-platform";
		WEBAUTHN_RP_ID: "auction.digitalglue.dev" | "staging-auction.digitalglue.dev";
		CALLS_API: "https://rtc.live.cloudflare.com";
		STRIPE_PUBLISHABLE_KEY: "pk_live_51SS6tIROT0tUNotJFFmI8edReNgDg18tRGC6cPA2vjGrb5iV1snk3cPHLMFnG1llsAI6nvUtQ34esKic4HIuLZUF00YMz6vkum";
		CALLS_APP_ID: string;
		CALLS_APP_SECRET: string;
		SESSION_DURABLE_OBJECT: DurableObjectNamespace<import("./src/worker").SessionDurableObject>;
		AUCTION_ROOM: DurableObjectNamespace<import("./src/worker").AuctionRoomDO>;
		LIVE_STORE: DurableObjectNamespace<import("./src/worker").LiveStore>;
		IMAGES: R2Bucket;
		DB: D1Database;
		IMPORT_QUEUE: Queue;
		BID_EVENTS_QUEUE: Queue;
		CHAT_EVENTS_QUEUE: Queue;
		ASSETS: Fetcher;
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "WEBAUTHN_APP_NAME" | "WEBAUTHN_RP_ID" | "CALLS_API" | "STRIPE_PUBLISHABLE_KEY" | "CALLS_APP_ID" | "CALLS_APP_SECRET">> {}
}
